-- Migration: Rename weight column to product_weight
-- Type: MANUAL - Requires Iceberg migration before applying
-- Author: Generated by Schema Evaluator
-- Date: 2026-01-26

-- ⚠️  WARNING: This is a MANUAL migration
-- ⚠️  You MUST run the Iceberg migration FIRST before applying this!
-- ⚠️  Follow the migration checklist in iceberg_migration_002.sql

-- ═══════════════════════════════════════════════════════════════
-- POSTGRES MIGRATION
-- ═══════════════════════════════════════════════════════════════

ALTER TABLE inventory.products RENAME COLUMN weight TO product_weight;

-- ═══════════════════════════════════════════════════════════════
-- MIGRATION CHECKLIST
-- ═══════════════════════════════════════════════════════════════
-- [ ] 1. Stop Debezium: docker-compose stop debezium
-- [ ] 2. Apply Iceberg migration (see iceberg_migration_002.sql)
-- [ ] 3. Verify Iceberg schema change
-- [ ] 4. Apply this Postgres migration: psql -f migrations/002_rename_weight_column.sql
-- [ ] 5. Restart Debezium: docker-compose start debezium
-- [ ] 6. Verify new data flows correctly (check Iceberg table)
-- [ ] 7. Update dbt models (see dbt_migration_002.sql)
-- [ ] 8. Run dbt: dbt run --select +products
-- [ ] 9. Run dbt tests: dbt test --select +products
-- [ ] 10. (Optional) Execute backfill if using Eager strategy
